package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"time"

	"github.com/shirisha/go-graphql/graph/model"
)

// CreatePost is the resolver for the CreatePost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Post, error) {
	Addpost := model.Post{
		Title:       input.Title,
		Content:     input.Content,
		Author:      *input.Author,
		Hero:        *input.Hero,
		PublishedAt: time.Now().Format("20-08-2022"),
		UpdatedAt:   time.Now().Format("20-08-2022"),
	}

	if err := r.Database.Create(&Addpost).Error; err != nil {
		fmt.Println(err)
		return nil, err

	}

	return &Addpost, nil
}

// UpdatePost is the resolver for the UpdatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, postID int, input *model.NewPost) (*model.Post, error) {
	Updatepost := model.Post{
		Title:     input.Title,
		Content:   input.Content,
		UpdatedAt: time.Now().Format("20-08-2022"),
	}

	if err := r.Database.Model(&model.Post{}).Where("id=?", postID).Updates(&Updatepost).Error; err != nil {
		fmt.Println(err)
		return nil, err
	}

	Updatepost.ID = postID
	return &Updatepost, nil
}

// CreateTodo is the resolver for the CreateTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	Addtodo := model.Todo{
		Title:     input.Title,
		Task:      input.Task,
		Status:    *input.Status,
		CreatedAt: time.Now().Format("20-08-2022"),
		UpdatedAt: time.Now().Format("20-08-2022"),
	}

	if err := r.Database.Create(&Addtodo).Error; err != nil {
		fmt.Println(err)
		return nil, err

	}

	return &Addtodo, nil
}

// UpdateTodo is the resolver for the UpdateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, todoID int, input *model.NewTodo) (*model.Todo, error) {
	Updatetodo := model.Todo{
		Title:     input.Title,
		Task:      input.Task,
		UpdatedAt: time.Now().Format("20-08-2022"),
	}

	if err := r.Database.Model(&model.Todo{}).Where("id=?", todoID).Updates(&Updatetodo).Error; err != nil {
		fmt.Println(err)
		return nil, err
	}

	Updatetodo.ID = todoID
	return &Updatetodo, nil
}

// GetAllPosts is the resolver for the GetAllPosts field.
func (r *queryResolver) GetAllPosts(ctx context.Context) ([]*model.Post, error) {
	posts := []*model.Post{}

	GetPosts := r.Database.Model(&posts).Find(&posts)

	if GetPosts.Error != nil {
		fmt.Println(GetPosts.Error)
		return nil, GetPosts.Error
	}
	return posts, nil
}

// GetOnePost is the resolver for the GetOnePost field.
func (r *queryResolver) GetOnePost(ctx context.Context, id int) (*model.Post, error) {
	post := model.Post{}

	if err := r.Database.Find(&post, id).Error; err != nil {
		fmt.Println(err)
		return nil, err
	}

	return &post, nil
}

// GetAllTodos is the resolver for the GetAllTodos field.
func (r *queryResolver) GetAllTodos(ctx context.Context) ([]*model.Todo, error) {
	todos := []*model.Todo{}

	GetTodos := r.Database.Model(&todos).Find(&todos)

	if GetTodos.Error != nil {
		fmt.Println(GetTodos.Error)
		return nil, GetTodos.Error
	}
	return todos, nil
}

// GetOneTodo is the resolver for the GetOneTodo field.
func (r *queryResolver) GetOneTodo(ctx context.Context, id int) (*model.Todo, error) {
	todo := model.Todo{}

	if err := r.Database.Find(&todo, id).Error; err != nil {
		fmt.Println(err)
		return nil, err
	}
	return &todo, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
