// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Title       string  `json:"Title"`
	Content     string  `json:"Content"`
	Author      *string `json:"Author,omitempty"`
	Hero        *string `json:"Hero,omitempty"`
	PublishedAt *string `json:"Published_At,omitempty"`
	UpdatedAt   *string `json:"Updated_At,omitempty"`
}

type NewTodo struct {
	Title     string  `json:"Title"`
	Task      string  `json:"Task"`
	Status    *string `json:"Status,omitempty"`
	CreatedAt *string `json:"Created_At,omitempty"`
	UpdatedAt *string `json:"Updated_At,omitempty"`
}

type Post struct {
	ID          int    `json:"id"`
	Title       string `json:"Title"`
	Content     string `json:"Content"`
	Author      string `json:"Author"`
	Hero        string `json:"Hero"`
	PublishedAt string `json:"Published_At"`
	UpdatedAt   string `json:"Updated_At"`
}

type Query struct {
}

type Todo struct {
	ID        int    `json:"id"`
	Title     string `json:"Title"`
	Task      string `json:"Task"`
	Status    string `json:"Status"`
	CreatedAt string `json:"Created_At"`
	UpdatedAt string `json:"Updated_At"`
}
